import { Workflow, WorkflowStep } from '../automation/types';
import { AICore } from '../core/AICore';
import { socialPublishing } from './SocialPublishingService';
import { notificationService } from './notification';
import { eventBus } from '../core/events/EventBus';
import { generateId } from '../lib/ids';
import { ExecutionTracker } from '../persistence/ExecutionTracker';
import { ActivityStream } from '../persistence/ActivityStream';

class WorkflowExecutionEngine {
  
  public async execute(workflow: Workflow, triggerData: any) {
    console.log(`[WorkflowEngine] Starting execution for: ${workflow.title}`);
    
    eventBus.publish({
       type: 'OPERATIONAL_LIVE_EVENT',
       source: 'WorkflowEngine',
       timestamp: Date.now(),
       payload: {
          id: generateId(),
          type: 'SYSTEM',
          message: `بدء تنفيذ الأتمتة: ${workflow.title}`,
          status: 'pending',
          timestamp: Date.now()
       }
    });

    const executionId = await ExecutionTracker.startExecution(workflow.brandId, workflow.id, triggerData?.type || 'manual');
    if (executionId) {
      await ActivityStream.log('workflow_started', `Workflow: ${workflow.id}`, { title: workflow.title }, workflow.brandId);
    }

    let context = { ...triggerData };
    let stepCount = 0;

    for (const step of workflow.steps) {
      if (step.id.includes('trigger')) continue; // Skip trigger nodes in execution loop

      try {
        stepCount++;
        context = await this.executeStep(step, workflow.brandId, context);
        if (executionId) {
           await ExecutionTracker.updateExecution(executionId, { currentStep: stepCount });
        }
      } catch (err) {
        console.error(`[WorkflowEngine] Step failed: ${step.title}`, err);
        if (executionId) {
           await ExecutionTracker.updateExecution(executionId, { status: 'failed' });
           await ActivityStream.log('workflow_failed', `Workflow: ${workflow.id}`, { error: String(err) }, workflow.brandId);
        }
        return; 
      }
    }

    if (executionId) {
       await ExecutionTracker.updateExecution(executionId, { status: 'completed' });
       await ActivityStream.log('workflow_completed', `Workflow: ${workflow.id}`, {}, workflow.brandId);
    }

    eventBus.publish({
       type: 'OPERATIONAL_LIVE_EVENT',
       source: 'WorkflowEngine',
       timestamp: Date.now(),
       payload: {
          id: generateId(),
          type: 'SYSTEM',
          message: `اكتملت الأتمتة بنجاح: ${workflow.title}`,
          status: 'success',
          timestamp: Date.now()
       }
    });
  }

  private async executeStep(step: WorkflowStep, brandId: string, context: any) {
    console.log(`[WorkflowEngine] Executing step: ${step.title} (${step.actionOrTriggerType})`);

    switch (step.actionOrTriggerType) {
      case 'GenerateContent':
        const gen = await AICore.generateContent({
           workspaceId: brandId,
           goal: `Generated by Automation: ${step.title}`,
           templateId: 'automation_post',
           params: { ...context, ...step.config }
        });
        return { ...context, lastContent: gen.content };

      case 'PublishPost':
        if (context.lastContent) {
           await socialPublishing.publishNow(brandId, ['twitter'], context.lastContent);
        }
        return context;

      case 'SendNotification':
        await notificationService.createNotification('system', `Automation: ${step.title}`, `تم تنفيذ خطوة بنجاح في ${step.title}`);
        return context;

      default:
        console.warn(`[WorkflowEngine] Unknown step type: ${step.actionOrTriggerType}`);
        return context;
    }
  }
}

export const workflowEngine = new WorkflowExecutionEngine();
